plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\K7ITServices\\arthala-allaiah-trust\\arthala-alleiah-charitable-trust\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]